#!/bin/sh

prefix=/usr/local
exec_prefix=${prefix}
usage="\
Usage: mpeg4ip-config [--prefix] [--exec-prefix] [--version] [--cflags] [--player-plugin-dir]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix)
      echo $prefix
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 1.6.1
      ;;
    --cflags)
      echo -g -O2 -DMPEG4IP -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
      ;;
    --player-plugin-dir)
      echo ${exec_prefix}/lib/mp4player_plugin
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
